begin;

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (length(btrim(body)) between 1 and 2000),
  created_at timestamptz not null default now(),
  check (sender_id <> recipient_id)
);

create index if not exists direct_messages_sender_created_idx on public.direct_messages(sender_id, created_at);
create index if not exists direct_messages_recipient_created_idx on public.direct_messages(recipient_id, created_at);

alter table public.direct_messages enable row level security;

drop policy if exists "Users can read their direct messages" on public.direct_messages;
create policy "Users can read their direct messages"
on public.direct_messages for select to authenticated
using (auth.uid() = sender_id or auth.uid() = recipient_id);

drop policy if exists "Users can send direct messages" on public.direct_messages;
create policy "Users can send direct messages"
on public.direct_messages for insert to authenticated
with check (auth.uid() = sender_id and auth.uid() <> recipient_id);

grant select, insert on public.direct_messages to authenticated;

create or replace function public.list_message_members()
returns table(user_id uuid, display_name text, username text, location text)
language sql stable security definer
set search_path = ''
as $$
  select
    p.user_id,
    coalesce(nullif(btrim(p.data->>'name'), ''), nullif(btrim(p.data->>'username'), ''), 'Wheeler') as display_name,
    coalesce(p.data->>'username', '') as username,
    coalesce(p.data->>'location', '') as location
  from public.profiles p
  where auth.uid() is not null
    and p.user_id <> auth.uid()
  order by lower(coalesce(nullif(btrim(p.data->>'name'), ''), nullif(btrim(p.data->>'username'), ''), 'Wheeler'));
$$;

revoke all on function public.list_message_members() from public;
grant execute on function public.list_message_members() to authenticated;

commit;
